import pytest
import os
import sys
import oracledb
from config import Config


sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from services.simulacion_service import (
    simular_mejora,
    determinar_iteraciones,
    determinar_k,
    modelo,
)

def get_oracle_connection():
    return oracledb.connect(
        user=Config.USUARIO,
        password=Config.PASSWORD,
        dsn=f"{Config.HOST}:{Config.PUERTO}/{Config.SERVICIO}"
    )

SCHEMA_SQL = """
BEGIN
   -- Borrar tablas si existen (para empezar de cero en cada test)
   FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN ('INSCRIPCIONES', 'ESTUDIANTES', 'MATERIAS', 'PROFESORES'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;

   -- Crear tablas
   EXECUTE IMMEDIATE 'CREATE TABLE estudiantes (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre VARCHAR2(100) NOT NULL,
       apellido VARCHAR2(100) NOT NULL,
       documento VARCHAR2(50) NOT NULL UNIQUE,
       carrera VARCHAR2(100) NOT NULL
   )';

   EXECUTE IMMEDIATE 'CREATE TABLE profesores (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre VARCHAR2(100) NOT NULL,
       apellido VARCHAR2(100) NOT NULL
   )';

   EXECUTE IMMEDIATE 'CREATE TABLE materias (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre VARCHAR2(100) NOT NULL,
       carrera VARCHAR2(100) NOT NULL
   )';

   EXECUTE IMMEDIATE 'CREATE TABLE inscripciones (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       estudiante_id NUMBER NOT NULL,
       materia_id NUMBER NOT NULL,
       nota_corte1 NUMBER(3,2) DEFAULT 0,
       CONSTRAINT fk_estudiante FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id) ON DELETE CASCADE,
       CONSTRAINT fk_materia FOREIGN KEY (materia_id) REFERENCES materias(id) ON DELETE CASCADE,
       CONSTRAINT uc_est_mat UNIQUE(estudiante_id, materia_id)
   )';

   -- Datos iniciales
   EXECUTE IMMEDIATE 'INSERT INTO materias (nombre, carrera) VALUES (''Cálculo Diferencial'', ''Ingeniería de Sistemas'')';
   EXECUTE IMMEDIATE 'INSERT INTO materias (nombre, carrera) VALUES (''Estructuras de Datos'', ''Ingeniería de Sistemas'')';
   EXECUTE IMMEDIATE 'INSERT INTO materias (nombre, carrera) VALUES (''Programación I'', ''Ingeniería de Sistemas'')';
   
   COMMIT;
END;
"""
@pytest.fixture(scope="session")
def setup_database():
    """Crea las tablas una sola vez para toda la sesión de pruebas."""
    conn = oracledb.connect(
        user=Config.USUARIO,
        password=Config.PASSWORD,
        dsn=f"{Config.HOST}:{Config.PUERTO}/{Config.SERVICIO}"
    )
    cursor = conn.cursor()
    cursor.execute(SCHEMA_SQL)
    conn.commit()
    cursor.close()
    conn.close()

@pytest.fixture()
def app_client(setup_database, monkeypatch):
    from app import app
    
    def _mock_get_conn():
        return oracledb.connect(
            user=Config.USUARIO,
            password=Config.PASSWORD,
            dsn=f"{Config.HOST}:{Config.PUERTO}/{Config.SERVICIO}"
        )

    import database.init_db as db_mod
    monkeypatch.setattr(db_mod, "get_connection", _mock_get_conn)

    app.config["TESTING"] = True
    with app.test_client() as client:
        yield client
    
    # LIMPIEZA AGRESIVA: Asegura que no queden datos para el próximo test
    conn = _mock_get_conn()
    cur = conn.cursor()
    try:
        cur.execute("DELETE FROM inscripciones")
        cur.execute("DELETE FROM estudiantes")
        conn.commit()
    finally:
        cur.close()
        conn.close()

# 1. PRUEBAS UNITARIAS — simulacion_service.py

class TestModelo:
    """Pruebas de la función diferencial dy/dt = k*(5 - y)"""

    def test_retorna_cero_cuando_y_igual_a_5(self):
        assert modelo(5, 0.05) == 0.0

    def test_retorna_positivo_cuando_y_menor_a_5(self):
        assert modelo(3.0, 0.05) > 0

    def test_retorna_negativo_cuando_y_mayor_a_5(self):
        assert modelo(5.5, 0.05) < 0

    def test_crece_mas_rapido_con_k_mayor(self):
        assert modelo(3.0, 0.1) > modelo(3.0, 0.05)


class TestDeterminarIteraciones:

    def test_nota_muy_alta_pocas_iteraciones(self):
        assert determinar_iteraciones(4.8) == 10

    def test_nota_media_iteraciones_moderadas(self):
        assert determinar_iteraciones(3.5) == 30

    def test_nota_baja_muchas_iteraciones(self):
        assert determinar_iteraciones(1.5) == 70

    def test_nota_limite_exacto_2_0(self):
        assert determinar_iteraciones(2.0) == 60

    def test_nota_limite_exacto_3_0(self):
        assert determinar_iteraciones(3.0) == 45

    def test_iteraciones_mayores_para_notas_menores(self):
        assert determinar_iteraciones(2.0) > determinar_iteraciones(3.0)
        assert determinar_iteraciones(3.0) > determinar_iteraciones(4.0)


class TestDeterminarK:

    def test_nota_alta_k_pequeno(self):
        assert determinar_k(4.5) == 0.03

    def test_nota_media_k_medio(self):
        assert determinar_k(3.5) == 0.045

    def test_nota_baja_k_grande(self):
        assert determinar_k(2.5) == 0.06

    def test_limite_exacto_3_0(self):
        assert determinar_k(3.0) == 0.045

    def test_limite_exacto_4_0(self):
        assert determinar_k(4.0) == 0.03


class TestSimularMejora:
    """Pruebas de integración del algoritmo RK4 completo."""

    def test_retorna_estructura_correcta(self):
        resultado = simular_mejora(3.0)
        assert "nota_inicial" in resultado
        assert "nota_final_estimada" in resultado
        assert "iteraciones" in resultado
        assert "historial" in resultado

    def test_nota_final_mayor_que_inicial(self):
        resultado = simular_mejora(3.0)
        assert resultado["nota_final_estimada"] > resultado["nota_inicial"]

    def test_nota_final_no_supera_5(self):
        resultado = simular_mejora(1.0)
        assert resultado["nota_final_estimada"] <= 5.0

    def test_nota_inicial_5_no_cambia(self):
        """Con y=5 el modelo retorna 0, no debe haber cambio."""
        resultado = simular_mejora(5.0)
        assert abs(resultado["nota_final_estimada"] - 5.0) < 0.01

    def test_historial_longitud_correcta(self):
        resultado = simular_mejora(3.0)
        # historial incluye el valor inicial + una entrada por iteración
        assert len(resultado["historial"]) == resultado["iteraciones"] + 1

    def test_historial_primer_valor_es_nota_inicial(self):
        resultado = simular_mejora(2.5)
        assert resultado["historial"][0] == 2.5

    def test_historial_es_monotono_creciente(self):
        resultado = simular_mejora(3.0)
        for i in range(1, len(resultado["historial"])):
            assert resultado["historial"][i] >= resultado["historial"][i - 1]

    def test_nota_muy_baja_mejora_significativamente(self):
        resultado = simular_mejora(1.0)
        assert resultado["nota_final_estimada"] > 2.0

    @pytest.mark.parametrize("nota", [1.0, 2.0, 3.0, 3.5, 4.0, 4.5, 4.9])
    def test_siempre_mejora_para_cualquier_nota_valida(self, nota):
        resultado = simular_mejora(nota)
        assert resultado["nota_final_estimada"] >= nota

# 2. PRUEBAS DE INTEGRACIÓN — Endpoints Flask

class TestEstudiantes:
    def test_crear_estudiante_exitoso(self, app_client):
        payload = {
            "nombre": "Ana", "apellido": "López",
            "documento": "UNIQUE_123", "carrera": "Sistemas"
        }
        rv = app_client.post("/estudiantes", json=payload)
        
        # Si esto falla, imprime el error para debuguear
        if rv.status_code != 201:
            print(f"\nError del Servidor: {rv.get_json()}")
            
        assert rv.status_code == 201

    def test_obtener_estudiante_por_id(self, app_client):
        # 1. Crear
        app_client.post("/estudiantes", json={
            "nombre": "María", "apellido": "Gómez",
            "documento": "DOC_456", "carrera": "Sistemas"
        })
        
        # 2. Obtener el ID dinámicamente
        res_lista = app_client.get("/estudiantes")
        estudiantes = res_lista.get_json()
        
        if not estudiantes:
            pytest.fail("No se creó el estudiante en la base de datos.")
            
        est_id = estudiantes[0]['id']

        # 3. Consultar
        rv = app_client.get(f"/estudiantes/{est_id}")
        assert rv.status_code == 200

class TestProfesores:

    def test_crear_profesor_exitoso(self, app_client):
        rv = app_client.post("/profesores", json={
            "nombre": "Jorge", "apellido": "Martínez"
        })
        assert rv.status_code == 201

    def test_crear_profesor_faltan_datos(self, app_client):
        rv = app_client.post("/profesores", json={"nombre": "Jorge"})
        assert rv.status_code == 400

    def test_listar_profesores(self, app_client):
        app_client.post("/profesores", json={"nombre": "Jorge", "apellido": "Martínez"})
        rv = app_client.get("/profesores")
        assert rv.status_code == 200
        assert len(rv.get_json()) >= 1

class TestMaterias:

    def test_listar_materias_con_datos_iniciales(self, app_client):
        rv = app_client.get("/materias")
        assert rv.status_code == 200
        assert len(rv.get_json()) >= 3  # las 3 del SCHEMA de prueba

    def test_crear_materia_exitosa(self, app_client):
        rv = app_client.post("/materias", json={
            "nombre": "Calidad de Software",
            "carrera": "Ingeniería de Sistemas"
        })
        assert rv.status_code == 201

    def test_crear_materia_faltan_datos(self, app_client):
        rv = app_client.post("/materias", json={"nombre": "Calidad de Software"})
        assert rv.status_code == 400

class TestInscripciones:
    def test_inscripcion_exitosa(self, app_client):
        # 1. Crear estudiante y obtener ID real
        app_client.post("/estudiantes", json={
            "nombre": "T", "apellido": "U", "documento": "INS_001", "carrera": "S"
        })
        est_id = app_client.get("/estudiantes").get_json()[0]['id']
        
        # 2. Obtener ID de materia (de las insertadas en el SCHEMA_SQL)
        materias = app_client.get("/materias").get_json()
        mat_id = materias[0]['id']
        
        # 3. Inscribir
        rv = app_client.post("/inscripciones", json={
            "estudiante_id": est_id, 
            "materia_id": mat_id
        })
        
        assert rv.status_code == 201

class TestSimulacionEndpoint:

    def test_simular_mejora_exitoso(self, app_client):
        rv = app_client.post("/simular-mejora", json={"nota_corte1": 3.0})
        assert rv.status_code == 200
        data = rv.get_json()
        assert "nota_final_estimada" in data
        assert "historial" in data

    def test_simular_sin_nota(self, app_client):
        rv = app_client.post("/simular-mejora", json={})
        assert rv.status_code == 400

    def test_simular_nota_limite_inferior(self, app_client):
        rv = app_client.post("/simular-mejora", json={"nota_corte1": 0.0})
        assert rv.status_code == 200

    def test_simular_nota_perfecta(self, app_client):
        rv = app_client.post("/simular-mejora", json={"nota_corte1": 5.0})
        assert rv.status_code == 200
        data = rv.get_json()
        assert abs(data["nota_final_estimada"] - 5.0) < 0.01

class TestProyeccion:

    def _setup_inscripcion_con_nota(self, client):
        client.post("/estudiantes", json={
            "nombre": "Test", "apellido": "User",
            "documento": "001", "carrera": "Sistemas"
        })
        client.post("/inscripciones", json={"estudiante_id": 1, "materia_id": 1})
        client.put("/inscripciones/1/notas", json={"nota_corte1": 3.2})

    def test_proyeccion_exitosa(self, app_client):
        self._setup_inscripcion_con_nota(app_client)
        rv = app_client.get("/proyeccion/1")
        assert rv.status_code == 200
        data = rv.get_json()
        assert "nota_final_estimada" in data
        assert "historial" in data

    def test_proyeccion_inscripcion_inexistente(self, app_client):
        rv = app_client.get("/proyeccion/999")
        assert rv.status_code == 404

    def test_proyeccion_sin_nota_registrada(self, app_client):
        app_client.post("/estudiantes", json={
            "nombre": "Test", "apellido": "User",
            "documento": "001", "carrera": "Sistemas"
        })
        app_client.post("/inscripciones", json={"estudiante_id": 1, "materia_id": 1})
        # nota_corte1 queda en 0 (DEFAULT), lo cual sí permite simular
        rv = app_client.get("/proyeccion/1")
        assert rv.status_code in (200, 400)