import pytest
import os
import sys
import oracledb
from config import Config

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from services.simulacion_service import (
    simular_mejora,
    determinar_iteraciones,
    determinar_k,
    modelo,
)

# ── Contraseña válida reutilizable ────────────────────────────────────────
PASSWORD_TEST = "Test1234!"

# ════════════════════════════════════════════════════════════════════════════
# HELPERS
# ════════════════════════════════════════════════════════════════════════════

def get_oracle_connection():
    return oracledb.connect(
        user=Config.USUARIO,
        password=Config.PASSWORD,
        dsn=f"{Config.HOST}:{Config.PUERTO}/{Config.SERVICIO}"
    )

def payload_estudiante(doc="12345678"):
    return {
        "nombre": "Test",
        "apellido": "Usuario",
        "documento": doc,
        "carrera": "Ingeniería de Sistemas",
        "password": PASSWORD_TEST,
        "acepta_tratamiento": True
    }

SCHEMA_SQL = """
BEGIN
   FOR r IN (SELECT table_name FROM user_tables
             WHERE table_name IN ('INSCRIPCIONES','ESTUDIANTES','MATERIAS','PROFESORES'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;

   EXECUTE IMMEDIATE 'CREATE TABLE estudiantes (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre VARCHAR2(100) NOT NULL,
       apellido VARCHAR2(100) NOT NULL,
       documento VARCHAR2(50) NOT NULL UNIQUE,
       carrera VARCHAR2(100) NOT NULL,
       password_hash VARCHAR2(256) NOT NULL
   )';

   EXECUTE IMMEDIATE 'CREATE TABLE profesores (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre VARCHAR2(100) NOT NULL,
       apellido VARCHAR2(100) NOT NULL
   )';

   EXECUTE IMMEDIATE 'CREATE TABLE materias (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nombre VARCHAR2(150) NOT NULL UNIQUE,
       carrera VARCHAR2(100) NOT NULL
   )';

   EXECUTE IMMEDIATE 'CREATE TABLE inscripciones (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       estudiante_id NUMBER NOT NULL,
       materia_id NUMBER NOT NULL,
       nota_corte1 NUMBER(3,2) DEFAULT 0,
       CONSTRAINT fk_est FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id) ON DELETE CASCADE,
       CONSTRAINT fk_mat FOREIGN KEY (materia_id) REFERENCES materias(id) ON DELETE CASCADE,
       CONSTRAINT uc_est_mat UNIQUE(estudiante_id, materia_id)
   )';

   EXECUTE IMMEDIATE 'INSERT INTO materias (nombre, carrera) VALUES (''Calculo Diferencial'', ''Ingeniería de Sistemas'')';
   EXECUTE IMMEDIATE 'INSERT INTO materias (nombre, carrera) VALUES (''Estructuras de Datos'', ''Ingeniería de Sistemas'')';
   EXECUTE IMMEDIATE 'INSERT INTO materias (nombre, carrera) VALUES (''Programacion I'', ''Ingeniería de Sistemas'')';

   COMMIT;
END;
"""

# ════════════════════════════════════════════════════════════════════════════
# FIXTURES
# ════════════════════════════════════════════════════════════════════════════

@pytest.fixture(scope="session")
def setup_database():
    conn = get_oracle_connection()
    cursor = conn.cursor()
    cursor.execute(SCHEMA_SQL)
    conn.commit()
    cursor.close()
    conn.close()

@pytest.fixture()
def app_client(setup_database, monkeypatch):
    import database.init_db as db_mod
    import services.inscripcion_service as ins_svc

    monkeypatch.setattr(db_mod, "get_connection", get_oracle_connection)
    monkeypatch.setattr(ins_svc, "get_connection", get_oracle_connection)

    from app import app
    app.config["TESTING"] = True

    with app.test_client() as client:
        yield client

    # Limpieza después de cada test
    conn = get_oracle_connection()
    cur = conn.cursor()
    try:
        cur.execute("DELETE FROM inscripciones")
        cur.execute("DELETE FROM estudiantes")
        cur.execute("DELETE FROM profesores")
        conn.commit()
    finally:
        cur.close()
        conn.close()

# ════════════════════════════════════════════════════════════════════════════
# 1. PRUEBAS UNITARIAS — simulacion_service.py
# ════════════════════════════════════════════════════════════════════════════

class TestModelo:
    def test_retorna_cero_cuando_y_igual_a_5(self):
        assert modelo(5, 0.05) == 0.0

    def test_retorna_positivo_cuando_y_menor_a_5(self):
        assert modelo(3.0, 0.05) > 0

    def test_retorna_negativo_cuando_y_mayor_a_5(self):
        assert modelo(5.5, 0.05) < 0

    def test_crece_mas_rapido_con_k_mayor(self):
        assert modelo(3.0, 0.1) > modelo(3.0, 0.05)


class TestDeterminarIteraciones:
    def test_nota_muy_alta_pocas_iteraciones(self):
        assert determinar_iteraciones(4.8) == 10

    def test_nota_media_iteraciones_moderadas(self):
        assert determinar_iteraciones(3.5) == 30

    def test_nota_baja_muchas_iteraciones(self):
        assert determinar_iteraciones(1.5) == 70

    def test_nota_limite_exacto_2_0(self):
        assert determinar_iteraciones(2.0) == 60

    def test_nota_limite_exacto_3_0(self):
        assert determinar_iteraciones(3.0) == 45

    def test_iteraciones_mayores_para_notas_menores(self):
        assert determinar_iteraciones(2.0) > determinar_iteraciones(3.0)
        assert determinar_iteraciones(3.0) > determinar_iteraciones(4.0)


class TestDeterminarK:
    def test_nota_alta_k_pequeno(self):
        assert determinar_k(4.5) == 0.03

    def test_nota_media_k_medio(self):
        assert determinar_k(3.5) == 0.045

    def test_nota_baja_k_grande(self):
        assert determinar_k(2.5) == 0.06

    def test_limite_exacto_3_0(self):
        assert determinar_k(3.0) == 0.045

    def test_limite_exacto_4_0(self):
        assert determinar_k(4.0) == 0.03


class TestSimularMejora:
    def test_retorna_estructura_correcta(self):
        resultado = simular_mejora(3.0)
        assert "nota_inicial" in resultado
        assert "nota_final_estimada" in resultado
        assert "iteraciones" in resultado
        assert "historial" in resultado

    def test_nota_final_mayor_que_inicial(self):
        resultado = simular_mejora(3.0)
        assert resultado["nota_final_estimada"] > resultado["nota_inicial"]

    def test_nota_final_no_supera_5(self):
        resultado = simular_mejora(1.0)
        assert resultado["nota_final_estimada"] <= 5.0

    def test_nota_inicial_5_no_cambia(self):
        resultado = simular_mejora(5.0)
        assert abs(resultado["nota_final_estimada"] - 5.0) < 0.01

    def test_historial_longitud_correcta(self):
        resultado = simular_mejora(3.0)
        assert len(resultado["historial"]) == resultado["iteraciones"] + 1

    def test_historial_primer_valor_es_nota_inicial(self):
        resultado = simular_mejora(2.5)
        assert resultado["historial"][0] == 2.5

    def test_historial_es_monotono_creciente(self):
        resultado = simular_mejora(3.0)
        for i in range(1, len(resultado["historial"])):
            assert resultado["historial"][i] >= resultado["historial"][i - 1]

    def test_nota_muy_baja_mejora_significativamente(self):
        resultado = simular_mejora(1.0)
        assert resultado["nota_final_estimada"] > 2.0

    @pytest.mark.parametrize("nota", [1.0, 2.0, 3.0, 3.5, 4.0, 4.5, 4.9])
    def test_siempre_mejora_para_cualquier_nota_valida(self, nota):
        resultado = simular_mejora(nota)
        assert resultado["nota_final_estimada"] >= nota


# ════════════════════════════════════════════════════════════════════════════
# 2. PRUEBAS DE INTEGRACIÓN — Endpoints Flask
# ════════════════════════════════════════════════════════════════════════════

class TestEstudiantes:

    def test_crear_estudiante_exitoso(self, app_client):
        rv = app_client.post("/estudiantes", json=payload_estudiante("11111111"))
        assert rv.status_code == 201

    def test_crear_estudiante_faltan_datos(self, app_client):
        rv = app_client.post("/estudiantes", json={"nombre": "Ana"})
        assert rv.status_code == 400

    def test_crear_estudiante_sin_aceptar_tratamiento(self, app_client):
        data = payload_estudiante("22222222")
        data["acepta_tratamiento"] = False
        rv = app_client.post("/estudiantes", json=data)
        assert rv.status_code == 400

    def test_crear_estudiante_password_debil(self, app_client):
        data = payload_estudiante("33333333")
        data["password"] = "1234"
        rv = app_client.post("/estudiantes", json=data)
        assert rv.status_code == 400

    def test_crear_estudiante_documento_duplicado(self, app_client):
        app_client.post("/estudiantes", json=payload_estudiante("44444444"))
        rv = app_client.post("/estudiantes", json=payload_estudiante("44444444"))
        assert rv.status_code == 400

    def test_listar_estudiantes_vacia(self, app_client):
        rv = app_client.get("/estudiantes")
        assert rv.status_code == 200
        assert rv.get_json() == []

    def test_listar_estudiantes_con_datos(self, app_client):
        app_client.post("/estudiantes", json=payload_estudiante("55555555"))
        rv = app_client.get("/estudiantes")
        assert rv.status_code == 200
        assert len(rv.get_json()) == 1

    def test_obtener_estudiante_por_id(self, app_client):
        app_client.post("/estudiantes", json=payload_estudiante("66666666"))
        lista = app_client.get("/estudiantes").get_json()
        est_id = lista[0]["id"]
        rv = app_client.get(f"/estudiantes/{est_id}")
        assert rv.status_code == 200
        assert rv.get_json()["nombre"] == "Test"

    def test_obtener_estudiante_inexistente(self, app_client):
        rv = app_client.get("/estudiantes/999999")
        assert rv.status_code == 404

    def test_eliminar_estudiante(self, app_client):
        app_client.post("/estudiantes", json=payload_estudiante("77777777"))
        lista = app_client.get("/estudiantes").get_json()
        est_id = lista[0]["id"]
        rv = app_client.delete(f"/estudiantes/{est_id}")
        assert rv.status_code == 200

    def test_eliminar_estudiante_inexistente(self, app_client):
        rv = app_client.delete("/estudiantes/999999")
        assert rv.status_code == 404


class TestProfesores:

    def test_crear_profesor_exitoso(self, app_client):
        rv = app_client.post("/profesores", json={
            "nombre": "Jorge", "apellido": "Martínez"
        })
        assert rv.status_code == 201

    def test_crear_profesor_faltan_datos(self, app_client):
        rv = app_client.post("/profesores", json={"nombre": "Jorge"})
        assert rv.status_code == 400

    def test_listar_profesores(self, app_client):
        app_client.post("/profesores", json={"nombre": "Jorge", "apellido": "Martínez"})
        rv = app_client.get("/profesores")
        assert rv.status_code == 200
        assert len(rv.get_json()) >= 1


class TestMaterias:

    def test_listar_materias_con_datos_iniciales(self, app_client):
        rv = app_client.get("/materias")
        assert rv.status_code == 200
        assert len(rv.get_json()) >= 3

    def test_crear_materia_exitosa(self, app_client):
        rv = app_client.post("/materias", json={
            "nombre": "Calidad de Software Test",
            "carrera": "Ingeniería de Sistemas"
        })
        assert rv.status_code == 201

    def test_crear_materia_faltan_datos(self, app_client):
        rv = app_client.post("/materias", json={"nombre": "Calidad de Software"})
        assert rv.status_code == 400


class TestInscripciones:

    def _crear_estudiante_id(self, client, doc="12345678"):
        client.post("/estudiantes", json=payload_estudiante(doc))
        return client.get("/estudiantes").get_json()[0]["id"]

    def _obtener_materia_id(self, client):
        return client.get("/materias").get_json()[0]["id"]

    def test_inscripcion_exitosa(self, app_client):
        est_id = self._crear_estudiante_id(app_client)
        mat_id = self._obtener_materia_id(app_client)
        rv = app_client.post("/inscripciones", json={
            "estudiante_id": est_id, "materia_id": mat_id
        })
        assert rv.status_code == 201

    def test_inscripcion_duplicada(self, app_client):
        est_id = self._crear_estudiante_id(app_client)
        mat_id = self._obtener_materia_id(app_client)
        app_client.post("/inscripciones", json={"estudiante_id": est_id, "materia_id": mat_id})
        rv = app_client.post("/inscripciones", json={"estudiante_id": est_id, "materia_id": mat_id})
        assert rv.status_code == 400

    def test_inscripcion_estudiante_inexistente(self, app_client):
        mat_id = self._obtener_materia_id(app_client)
        rv = app_client.post("/inscripciones", json={
            "estudiante_id": 999999, "materia_id": mat_id
        })
        assert rv.status_code == 404

    def test_inscripcion_materia_inexistente(self, app_client):
        est_id = self._crear_estudiante_id(app_client)
        rv = app_client.post("/inscripciones", json={
            "estudiante_id": est_id, "materia_id": 999999
        })
        assert rv.status_code == 404

    def test_inscripcion_faltan_datos(self, app_client):
        rv = app_client.post("/inscripciones", json={"estudiante_id": 1})
        assert rv.status_code == 400

    def test_listar_inscripciones(self, app_client):
        est_id = self._crear_estudiante_id(app_client)
        mat_id = self._obtener_materia_id(app_client)
        app_client.post("/inscripciones", json={"estudiante_id": est_id, "materia_id": mat_id})
        rv = app_client.get("/inscripciones")
        assert rv.status_code == 200
        data = rv.get_json()
        assert len(data) >= 1
        assert "estudiante" in data[0]
        assert "materia" in data[0]

    def test_actualizar_nota_corte1(self, app_client):
        est_id = self._crear_estudiante_id(app_client)
        mat_id = self._obtener_materia_id(app_client)
        app_client.post("/inscripciones", json={"estudiante_id": est_id, "materia_id": mat_id})
        ins_id = app_client.get("/inscripciones").get_json()[0]["id"]
        rv = app_client.put(f"/inscripciones/{ins_id}/notas", json={"nota_corte1": 3.5})
        assert rv.status_code == 200

    def test_actualizar_nota_inscripcion_inexistente(self, app_client):
        rv = app_client.put("/inscripciones/999999/notas", json={"nota_corte1": 3.5})
        assert rv.status_code == 404


class TestSimulacionEndpoint:

    def test_simular_mejora_exitoso(self, app_client):
        rv = app_client.post("/simular-mejora", json={"nota_corte1": 3.0})
        assert rv.status_code == 200
        data = rv.get_json()
        assert "nota_final_estimada" in data
        assert "historial" in data

    def test_simular_sin_nota(self, app_client):
        rv = app_client.post("/simular-mejora", json={})
        assert rv.status_code == 400

    def test_simular_nota_limite_inferior(self, app_client):
        rv = app_client.post("/simular-mejora", json={"nota_corte1": 0.0})
        assert rv.status_code == 200

    def test_simular_nota_perfecta(self, app_client):
        rv = app_client.post("/simular-mejora", json={"nota_corte1": 5.0})
        assert rv.status_code == 200
        data = rv.get_json()
        assert abs(data["nota_final_estimada"] - 5.0) < 0.01


class TestProyeccion:

    def _setup(self, client):
        client.post("/estudiantes", json=payload_estudiante("98765432"))
        est_id = client.get("/estudiantes").get_json()[0]["id"]
        mat_id = client.get("/materias").get_json()[0]["id"]
        client.post("/inscripciones", json={"estudiante_id": est_id, "materia_id": mat_id})
        ins_id = client.get("/inscripciones").get_json()[0]["id"]
        client.put(f"/inscripciones/{ins_id}/notas", json={"nota_corte1": 3.2})
        return ins_id

    def test_proyeccion_exitosa(self, app_client):
        ins_id = self._setup(app_client)
        rv = app_client.get(f"/proyeccion/{ins_id}")
        assert rv.status_code == 200
        data = rv.get_json()
        assert "nota_final_estimada" in data
        assert "historial" in data

    def test_proyeccion_inscripcion_inexistente(self, app_client):
        rv = app_client.get("/proyeccion/999999")
        assert rv.status_code == 404

    def test_proyeccion_sin_nota_registrada(self, app_client):
        client = app_client
        client.post("/estudiantes", json=payload_estudiante("11223344"))
        est_id = client.get("/estudiantes").get_json()[0]["id"]
        mat_id = client.get("/materias").get_json()[0]["id"]
        client.post("/inscripciones", json={"estudiante_id": est_id, "materia_id": mat_id})
        ins_id = client.get("/inscripciones").get_json()[0]["id"]
        rv = client.get(f"/proyeccion/{ins_id}")
        assert rv.status_code in (200, 400)